apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-db-secret
  namespace: ecommerce
type: Opaque
stringData:
  DB_HOST: "terraform-442b390f494608134dcfa2f355.cb6uiekc8zcj.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "mysqleks"
  DB_USERNAME: "admin"
  DB_PASSWORD: "Akhilesh6309"
