apiVersion: v1
kind: Service

metadata:
  name: ecommerce-backend
  namespace: {{ .Values.namespace }}

spec:
  type: ClusterIP

  selector:
    app: ecommerce-backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
