apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-backend
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: ecommerce-backend

  template:
    metadata:
      labels:
        app: ecommerce-backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          env:
            - name: SERVER_PORT
              value: "8080"

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ecommerce-db-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ecommerce-db-secret
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-db-secret
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-db-secret
                  key: DB_PASSWORD

            - name: DDL_AUTO
              value: "update"

            - name: SQL_INIT_MODE
              value: "always"

            - name: CORS_ALLOWED_ORIGINS
              value: "*"

          resources:
{{ toYaml .Values.backend.resources | indent 12 }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 20
