apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-frontend
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: ecommerce-frontend

  template:
    metadata:
      labels:
        app: ecommerce-frontend

    spec:
      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: {{ .Values.frontend.containerPort }}

          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}

          readinessProbe:
            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 20
            periodSeconds: 20
