apiVersion: v1
kind: Service

metadata:
  name: ecommerce-frontend
  namespace: {{ .Values.namespace }}

spec:
  type: ClusterIP

  selector:
    app: ecommerce-frontend

  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
