frontend:
  image:
    repository: "648967983842.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-frontend"
    tag: "6e3a385"

backend:
  image:
    repository: "648967983842.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-backend"
    tag: "6e3a385"

database:
  host: "terraform-442b390f494608134dcfa2f355.cb6uiekc8zcj.ap-south-1.rds.amazonaws.com"
  port: "3306"
  name: "mysqleks"
  username: "admin"
  password: "Akhilesh6309"

ingress:
  host: http://infocontent.site
  certificateArn: "arn:aws:acm:ap-south-1:648967983842:certificate/854757e7-2ecf-4dab-b2cf-762071e0bbcd"
